on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/actions/**'
  pull_request:
    paths-ignore:
      - '.github/actions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # previous LTS version
          - SONAR_SERVER_VERSION: 8.9.10
            SONAR_PLUGIN_API_VERSION: 6.7.7
            SONAR_JAVA_VERSION: 7.11.0.29148
            SONAR_SERVER_JAVA_VERSION: 11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.SONAR_SERVER_JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
                    ${{ runner.os }}-gradle-
      - name: Build
        run: |
          ./gradlew build --build-cache --no-daemon \
            -PsonarPluginApiVersion=${{ matrix.SONAR_PLUGIN_API_VERSION }} \
            -PsonarJavaVersion=${{ matrix.SONAR_JAVA_VERSION }}