on:
  pull_request:
    paths-ignore:
      - '.github/actions/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # previous LTS version
          - SONAR_SERVER_VERSION: 8.9.10
            SONAR_PLUGIN_API_VERSION: 6.7.7
            SONAR_JAVA_VERSION: 7.11.0.29148
            SONAR_SERVER_JAVA_VERSION: 11
          - SONAR_SERVER_VERSION: 9.7.0.61563
            SONAR_PLUGIN_API_VERSION: 6.7.7
            SONAR_JAVA_VERSION: 7.13.0.29990
            SONAR_SERVER_JAVA_VERSION: 11
          # current LTS version
          - SONAR_SERVER_VERSION: 9.9.0.65466
            SONAR_PLUGIN_API_VERSION: 6.7.7
            SONAR_JAVA_VERSION: 7.13.0.29990
            SONAR_SERVER_JAVA_VERSION: 17
          - SONAR_SERVER_VERSION: 10.0.0.68432
            SONAR_PLUGIN_API_VERSION: 6.7.7
            SONAR_JAVA_VERSION: 7.13.0.29990
            SONAR_SERVER_JAVA_VERSION: 17
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.SONAR_SERVER_JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.SONAR_SERVER_JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
                    ${{ runner.os }}-gradle-
      - name: Build
        run: |
          ./gradlew build sonar --build-cache --no-daemon \
            -PsonarPluginApiVersion=${{ matrix.SONAR_PLUGIN_API_VERSION }} \
            -PsonarJavaVersion=${{ matrix.SONAR_JAVA_VERSION }} \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.pullrequest.provider=github \
            -Dsonar.pullrequest.github.repository=${{ github.repository }} \
            -Dsonar.pullrequest.key=${{ github.event.number }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
